name: yawa4u
description: "Yet Another Workout App for You"

publish_to: "none" # Remove this line if you wish to publish to pub.dev

# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.1

environment:
  sdk: ^3.10.0

dependencies:
  csv: ^6.0.0
  feedback_sentry: ^3.2.0
  firebase_core: ^4.2.1
  firebase_analytics: ^12.0.4
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4
  flutter_riverpod: ^3.0.3
  go_router: ^17.0.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  intl: ^0.20.2
  json_annotation: ^4.9.0
  logging: ^1.3.0
  path: ^1.9.1
  path_provider: ^2.1.5
  sentry_flutter: ^9.8.0
  shared_preferences: ^2.5.3
  url_launcher: ^6.3.2
  flutter_slidable: ^4.0.3
  cupertino_icons: ^1.0.8
  file_picker: ^10.3.6
  share_plus: ^12.0.1
  youtube_player_flutter: ^9.1.3
  riverpod: ^3.0.3
  riverpod_annotation: ^3.0.3
  uuid: ^4.5.2
  package_info_plus: ^9.0.0
  # WiFi Sync dependencies
  shelf: ^1.4.2
  shelf_router: ^1.1.4
  qr_flutter: ^4.1.0
  mobile_scanner: ^6.0.2
  network_info_plus: ^6.1.3
  http: ^1.2.2
  device_info_plus: ^11.2.1
  table_calendar: ^3.2.0
  # Custom Theme Creation dependencies
  image_picker: ^1.1.2
  flutter_image_compress: ^2.3.0
  palette_generator: ^0.3.3+4

dev_dependencies:
  sentry_dart_plugin: ^3.2.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

  # Code generation
  hive_generator: ^2.0.1
  build_runner: ^2.4.13
  json_serializable: ^6.8.0
  flutter_native_splash: ^2.4.7

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/templates/
    - exercises.csv
    - assets/images/
    - assets/common/
    - assets/backgrounds/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package

sentry:
  upload_debug_symbols: true
  upload_source_maps: true
  project: yawa
  org: blairhouse-apps

# Flutter Launcher Icons configuration
flutter_launcher_icons:
  ios: true
  android: true
  image_path_ios: "assets/common/yawa4u-icon-dark.png"
  image_path_ios_dark_transparent: "assets/common/yawa4u-icon-mask.png"
  image_path_android: "assets/common/yawa4u-icon-dark.png"
  adaptive_icon_background: "assets/common/yawa4u-icon-dark.png"
  adaptive_icon_foreground: "assets/common/yawa4u-icon-mask.png"
  remove_alpha_ios: true
  web:
    generate: true
    image_path: "assets/common/yawa4u-icon-dark.png"

# Flutter Native Splash configuration
flutter_native_splash:
  # color: "#ffffff"
  background_image: assets/images/rhino_rack.png
  image: "assets/android/app-icon-foreground.png"
  android_12:
    color: "#ffffff"
    icon_background_color: "#FFFFFF"
    image: "assets/images/yawa4u-icon-mask.png"
